"""empty message

Revision ID: 81ea8b375a2b
Revises: ae740f3c11c4
Create Date: 2026-01-02 15:15:19.038386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ea8b375a2b'
down_revision = 'ae740f3c11c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playstyle', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('playstyle')

    # ### end Alembic commands ###
