"""add tank advanced stats

Revision ID: bd20105425f8
Revises: 81ea8b375a2b
Create Date: 2026-01-07 16:27:12.971108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd20105425f8'
down_revision = '81ea8b375a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hit_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gun_caliber', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reload_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penetration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alpha_damage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('top_speed', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('tier',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tank_class',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.alter_column('tank_class',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('top_speed')
        batch_op.drop_column('alpha_damage')
        batch_op.drop_column('penetration')
        batch_op.drop_column('reload_time')
        batch_op.drop_column('gun_caliber')
        batch_op.drop_column('hit_points')

    # ### end Alembic commands ###
